### ISSUE TITLE
Can't install Miniconda

### ISSUE THREAD

**Issue by hiramf** [Microsoft/ELL#61]
Following these steps:

    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh
    chmod +x Miniconda3-latest-Linux-armv7l.sh
    ./Miniconda3-latest-Linux-armv7l.sh

I get to License Agreement and after I enter 'yes', I just get a series of 'y' repeating to infinity. Help?

    y
    y
    y
    y
    y
    y
    y

**Comment by lisaong** [comment]
I see your post on Raspberry Pi / Stack Exchange: https://raspberrypi.stackexchange.com/questions/70261/cant-install-miniconda-3

Unfortunately I don't have more helpful information to give, because this is part of the installation script created by Continuum / Anaconda.  It's a blob to us....

If you haven't done so already, try the -f option (see https://conda.io/docs/troubleshooting.html#fix-broken-conda), and also try a brand new Raspberry Pi SD card image to rule out other environment issues.
