### ISSUE TITLE
Low FPS on RPi 3 (1 fps)

### ISSUE THREAD

**Issue by hiramf** [Microsoft/ELL#65]
Finally got it up and running!

What is everyone getting as their FPS? Right now, I'm barely getting 1.0 fps and extreme lag (4 seconds).

Raspberry Pi 3, PiCam v2

**Comment by saurabhvyas** [comment]
will it work on esp32 ?

**Comment by Dezorian** [comment]
Same FPS 0.7-0.8 on my RPi3. You could try overclocking it if you need it faster.
But for a CNN i've heard that this performance is already pretty awesome! CNTK network didnt even load because of the size of net file >512MB wich is too large for the rpi. Sticking to darknet and training my own data!

**Comment by Dezorian** [comment]
> will it work on esp32 ?
I seriously doubt it.

**Comment by lovettchris** [comment]
I opened [separate issue about esp32](https://github.com/Microsoft/ELL/issues/78).
